### ISSUE TITLE
Debian 9.5 x64 Stretch - build problem version 1.1.0

### ISSUE THREAD

**Issue by Aminuxer** [anonymousbitcoin/anon#60] opened 2018-09-17 12:50 UTC
Hello.

I try to build version anon-1.1.0 with master node fixes 
https://github.com/anonymousbitcoin/anon/releases/tag/1.1.0
but got this error:
```
...
checking for visibility attribute... yes
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing, Bitcoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)
```
apt :
libdb5.3++ is already the newest version (5.3.28-12+deb9u1).
libdb5.3++-dev is already the newest version (5.3.28-12+deb9u1)

How to build version 1.1.0 on Debian 9.5 ?
Thank you.

**Comment by nlevo** [comment] 2018-09-17 18:19
If I remember right, you need to have libdb4.8. Delete libdb5.3++ and install sudo apt-get install libdb4.8++

**Comment by nlevo** [comment] 2019-01-11 15:33
Closing this issue due to lack of user response. If the issue is still a problem, feel free to reopen this ticket.

**Closed by nlevo** 2019-01-11 15:33 UTC
